name: Build and Release Executables

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build for ${{ matrix.desc }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # ===== Linux =====
          - os: linux
            arch: x86_64
            runs_on: ubuntu-22.04
            py_arch: x64
            desc: linux-x86_64

          # ===== Windows =====
          - os: windows
            arch: x86_64
            runs_on: windows-2022
            py_arch: x64
            desc: windows-x86_64

          # ===== macOS =====
          # macOS-13 为 Intel x86_64，macOS-14 为 Apple Silicon arm64
          - os: macos
            arch: x86_64
            runs_on: macos-13
            py_arch: x64
            desc: macos-x86_64
          - os: macos
            arch: arm64
            runs_on: macos-14
            py_arch: arm64
            desc: macos-arm64

    runs-on: ${{ matrix.runs_on }}

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 安装对应架构的 Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: ${{ matrix.py_arch }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pyinstaller
        shell: bash

      - name: Build with PyInstaller
        run: |
          mkdir -p dist
          pyinstaller --onefile --name TJUEcardSetup setup.py
          pyinstaller --onefile --noconsole --name TJUEcard main.py
        shell: bash

      # ===== 验证架构 =====
      - name: Check binary arch (Linux)
        if: runner.os == 'Linux'
        run: |
          file "dist/TJUEcardSetup"
          file "dist/TJUEcard"
        shell: bash

      - name: Check binary arch (macOS)
        if: runner.os == 'macOS'
        run: |
          lipo -info "dist/TJUEcardSetup" || true
          lipo -info "dist/TJUEcard" || true
        shell: bash

      - name: Check binary arch (Windows)
        if: runner.os == 'Windows'
        run: |
          if (Get-Command dumpbin -ErrorAction SilentlyContinue) {
            dumpbin /headers "dist\TJUEcardSetup.exe" | Select-String -Pattern "machine"
            dumpbin /headers "dist\TJUEcard.exe" | Select-String -Pattern "machine"
          } else {
            Write-Host "dumpbin not found; skipping arch check."
          }
        shell: pwsh

      - name: Package (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          set -eux
          cd dist
          tar -czf "TJUEcard-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref_name }}.tar.gz" \
            "TJUEcardSetup" \
            "TJUEcard"
          ls -l "TJUEcard-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref_name }}.tar.gz"
        shell: bash

      - name: Package (Windows)
        if: runner.os == 'Windows'
        run: |
          Set-StrictMode -Version Latest
          Set-Location dist
          Compress-Archive -Path "TJUEcardSetup.exe","TJUEcard.exe" -DestinationPath "TJUEcard-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref_name }}.zip"
          Get-ChildItem "TJUEcard-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref_name }}.zip" | Format-List
        shell: pwsh

      # ===== 生成 SHA256 校验和 =====
      - name: SHA256 (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          cd dist
          shasum -a 256 "TJUEcard-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref_name }}.tar.gz" > "TJUEcard-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref_name }}.tar.gz.sha256"
          cat "TJUEcard-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref_name }}.tar.gz.sha256"
        shell: bash

      - name: SHA256 (Windows)
        if: runner.os == 'Windows'
        run: |
          Set-Location dist
          certutil -hashfile "TJUEcard-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref_name }}.zip" SHA256 | `
            Select-String -NotMatch "hash of file|CertUtil|^$" | `
            ForEach-Object { $_.Line } | `
            Out-File -Encoding ascii "TJUEcard-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref_name }}.zip.sha256"
          Get-Content "TJUEcard-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref_name }}.zip.sha256"
        shell: pwsh

      # ===== 上传到 Release：只上传打包文件（和校验和） =====
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/TJUEcard-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref_name }}.${{ runner.os == 'Windows' && 'zip' || 'tar.gz' }}
            dist/TJUEcard-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref_name }}.${{ runner.os == 'Windows' && 'zip.sha256' || 'tar.gz.sha256' }}
