name: Sync GitHub Release to Gitee

on:
    workflow_dispatch:

jobs:
    sync:
        runs-on: ubuntu-latest
        env:
            GITEE_OWNER: ${{ secrets.GITEE_USER_NAME }}
            GITEE_REPO: TJUEcard
            GITEE_API: https://gitee.com/api/v5
        steps:
            - name: Checkout (not strictly needed)
              uses: actions/checkout@v4

            - name: Prepare tools
              run: |
                  sudo apt-get update
                  sudo apt-get install -y jq curl

            - name: Capture context & download assets (latest release)
              id: ctx
              env:
                  GITHUB_REPOSITORY: ${{ github.repository }}
              shell: bash
              run: |
                  set -Eeuo pipefail

                  # 1) 拉取最新 release (含 assets)
                  RESP=$(
                    curl -fsSL \
                      -H 'Accept: application/vnd.github+json' \
                      -H 'User-Agent: release-sync-action' \
                      "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest"
                  )

                  # 2) 输出 JSON 给后续步骤使用
                  TAG=$(jq -r '.tag_name' <<<"$RESP")
                  NAME=$(jq -r '.name // empty' <<<"$RESP")
                  BODY=$(jq -r '.body // empty' <<<"$RESP")
                  echo "tag=$TAG"   >> "$GITHUB_OUTPUT"
                  echo "name=$NAME" >> "$GITHUB_OUTPUT"
                  echo "body=$(jq -Rn --arg s "$BODY" '$s')" >> "$GITHUB_OUTPUT"  # 已是合法 JSON 字符串

                  # 3) 下载所有资产 (保留原名)
                  mkdir -p assets
                  COUNT=$(jq -r '.assets|length' <<<"$RESP")
                  if [ "$COUNT" = "0" ] || [ -z "$COUNT" ]; then
                    echo "No assets found on release ${TAG}."
                    exit 0
                  fi

                  jq -r '.assets[] | [.name, .browser_download_url] | @tsv' <<<"$RESP" \
                  | while IFS=$'\t' read -r NAME URL; do
                      echo "Downloading ${NAME} ..."
                      curl -fL --retry 3 --retry-delay 2 -o "assets/${NAME}" "$URL"
                    done

                  # 如需额外同步源码包, 取消下面两行注释即可
                  # ZIPURL=$(jq -r '.zipball_url' <<<"$RESP"); [ -n "$ZIPURL" ] && curl -fL -o "assets/source-${TAG}.zip" "$ZIPURL"
                  # TARURL=$(jq -r '.tarball_url' <<<"$RESP"); [ -n "$TARURL" ] && curl -fL -o "assets/source-${TAG}.tar.gz" "$TARURL"

            - name: Ensure Release exists on Gitee (create if missing)
              id: gitee_release
              env:
                  GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
              run: |
                  set -euo pipefail
                  TAG='${{ steps.ctx.outputs.tag }}'
                  NAME='${{ steps.ctx.outputs.name }}'
                  BODY_JSON='${{ steps.ctx.outputs.body }}' # 已是 JSON 字符串

                  echo "Ensuring release for tag $TAG on Gitee ..."

                  # 1) 尝试按 tag 获取 release
                  set +e
                  RESP=$(curl -s -w "\n%{http_code}" \
                    "$GITEE_API/repos/$GITEE_OWNER/$GITEE_REPO/releases/tags/$TAG?access_token=$GITEE_TOKEN")
                  BODY=$(sed '$d' <<< "$RESP")
                  CODE=$(tail -n1 <<< "$RESP")
                  set -e

                  if [ "$CODE" = "200" ]; then
                    RID=$(jq -r '.id' <<< "$BODY")
                    echo "Found existing release id: $RID"
                  else
                    echo "Release not found on Gitee, creating..."
                    # 2) 创建 release
                    CREATE=$(curl -sS -X POST "$GITEE_API/repos/$GITEE_OWNER/$GITEE_REPO/releases" \
                      -H "Content-Type: application/json" \
                      -d "{
                            \"access_token\": \"${GITEE_TOKEN}\",
                            \"tag_name\": \"${TAG}\",
                            \"name\": ${NAME:+\"$NAME\"},
                            \"body\": ${BODY_JSON:-\"\"},
                            \"prerelease\": false,
                            \"draft\": false
                          }")
                    RID=$(jq -r '.id' <<< "$CREATE")
                    if [ "$RID" = "null" ] || [ -z "$RID" ]; then
                      echo "Failed to create release on Gitee:"
                      echo "$CREATE"
                      exit 1
                    fi
                    echo "Created Gitee release id: $RID"
                  fi

                  echo "rid=$RID" >> $GITHUB_OUTPUT

            - name: Upload ALL assets to Gitee Release (keep names)
              env:
                  GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
              run: |
                  set -euo pipefail
                  RID='${{ steps.gitee_release.outputs.rid }}'

                  shopt -s nullglob
                  FILES=(assets/*)
                  if [ ${#FILES[@]} -eq 0 ]; then
                    echo "No local assets to upload."
                    exit 0
                  fi

                  for f in "${FILES[@]}"; do
                    NAME=$(basename "$f")
                    echo "Uploading $NAME to Gitee release $RID ..."
                    # Gitea/Gitee 接口使用 multipart/form-data 的 attachment 字段
                    # POST /repos/{owner}/{repo}/releases/{id}/assets?name=FILENAME
                    RESP=$(curl -sS -X POST \
                      "$GITEE_API/repos/$GITEE_OWNER/$GITEE_REPO/releases/$RID/assets?access_token=$GITEE_TOKEN&name=$(printf %s "$NAME" | jq -sRr @uri)" \
                      -F "attachment=@$f")
                    URL=$(jq -r '.browser_download_url // .download_url // empty' <<< "$RESP")
                    if [ -z "$URL" ]; then
                      echo "Upload failed for $NAME:"
                      echo "$RESP"
                      exit 1
                    else
                      echo "Uploaded: $URL"
                    fi
                  done